---
# SPDX-FileCopyrightText: 2026 The .github development team
#
# SPDX-License-Identifier: CC0-1.0
name: Check formatting of the project
on: [push, pull_request]
jobs:
  yamlfix:
    name: Check YAML formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Create requirements file for setup-python
        run: touch ./requirements.txt
      - name: Install Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
          cache: pip
      - name: Install yamlfix
        run: pip install yamlfix
      - name: Check YAML formatting
        run: yamlfix -v --check .
  mdformat:
    name: Check Markdown formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Create requirements file for setup-python
        run: touch ./requirements.txt
      - name: Install Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
          cache: pip
      - name: Install Mdformat
        run: pip install mdformat
      - name: Check Markdown formatting
        run: mdformat --check .
  svgo:
    name: Check formatting with svgo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: '10'
          standalone: true
      - name: Check SVG formatting
        run: |-
          git ls-files -z -- '*.svg' | xargs -0 -r pnpx svgo --pretty
          git diff --exit-code
